# -*- coding: utf-8 -*-
"""lesson1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TOadkbgLXg9X93sVZGgfNlLpIjGxLRka

# Домашнее задание № 1
## Тема "Высшая математика"
### Формулировка задания:
1. Решить задачи по высшей математике
2. Решить матрицы

"""

import numpy as np

matrix1 = [[6, -8, 3]]

matrix2 = [[1],
           [1],
           [4]]

A = np.matrix(matrix1)

B = np.matrix(matrix2)

C = A * B

print(C)

matrix3 = [[-3, -7],
           [-10, 6],
           [0, -6],
           [-1, -3]]

matrix4 = [[-8, 9],
           [4, -2]]

D = np.matrix(matrix3)

E = np.matrix(matrix4)

F = D * E

print(F)

"""# Без Numpy"""

def matrix(param1, param2):
  result = []
  for i in range(len(param1)):
    temp = []
    for j in range(len(param2[0])):
      temp.append(0)
    result.append(temp)
  for i in range(len(param1)):
    for j in range(len(param2[0])):
      for k in range(len(param1[0])):
        result[i][j] += param1[i][k] * param2[k][j]
  return result

print(matrix(matrix1, matrix2))

print(matrix(matrix3, matrix4))